### ISSUE TITLE
Motifs

### ISSUE THREAD

**Issue by Barikad** [samueltardieu/AusweisBot#1]
Bravo pour le travail. 
De mon côté je tente de monter un bot avec la même idée depuis quelques jours
Une question néanmoins: Pourquoi avoir retenu uniquement deux motifs de déplacement. Par exemple le motif concernant les déplacement professionnel n'apparaît pas.

**Comment by samueltardieu** [comment]
Tous les motifs sont prévus et sont accessibles à travers la commande `/autre`, ces deux là sont juste placés en raccourci car ce sont les plus fréquemment utilisés. Pour les déplacements professionnels, vous pouvez par exemple taper `/autre travail` et le bot vous enverra le justificatif demandé.

Je vais rajouter, lorsque les données personnelles sont saisies, une référence explicite à la commande `/help` qui permet d'obtenir l'aide du bot dans laquelle ces motifs sont détaillés (je vous invite à l'utiliser).
