### ISSUE TITLE
Incorrect PDF template for

### ISSUE THREAD

**Issue by xuctar** [samueltardieu/AusweisBot#110]
PDF template is not correct for sport: there is no time restriction and the radius is 10 km.
Thanks for your work it's a great bot.

**Comment by samueltardieu** [comment]
Unfortunately I use the template coming from https://media.interieur.gouv.fr/attestation-deplacement-derogatoire-covid-19/ which reads right now

> L'attestation de déplacement dérogatoire téléchargeable au format numérique est actuellement en cours de mise à jour. Si vous devez vous déplacer, vous pouvez utiliser l'attestation de déplacement dérogatoire disponible aux formats .pdf, .docx et .txt, sur le site du ministère de l'Intérieur : https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestations-de-deplacement"

**Comment by xuctar** [comment]
Ok thanks

**Comment by samueltardieu** [comment]
Note that TousAntiCovid isn't up-to-date either… I'll see what I can do though.

**Comment by xuctar** [comment]
Yes PDF is updated but not digital template, very strange :D

**Comment by samueltardieu** [comment]
A manually modified PDF has been installed. You can now use `/sport` and get a certificate with no time limit and a 10km radius.

**Comment by xuctar** [comment]
Great, thanks
