### ISSUE TITLE
DB Access

### ISSUE THREAD

**Issue by lezioul** [samueltardieu/AusweisBot#39]
Bonsoir,

j'essaye d'héberger ce bot sur un vps pour la famille.
J'ai un soucis d'accès à couchDb (je ne sais pas ou passer les credentials dans la config) est ce qu'il y a une config particulière à adopter côté serveur de données pour autoriser l'accès?

Merci

**Comment by samueltardieu** [comment]
Bonsoir.

Le bot est prévu pour utiliser une base de données non protégée dans le cadre d'un `docker-compose`. La base de données n'est accessible que depuis le docker qui lance le bot sur un réseau virtuel privé, du coup il n'y a pas de problème de sécurité d'accès.

Il suffit de créer un fichier `.env` contenant les variables `TELEGRAM_TOKEN` et `CONTACT_EMAIL`, puis de récupérer la dernière image (elle est maintenant sur DockerHub, compilée à chaque fois qu'une modification entre dans le dépôt) et de lancer le tout, avec :

```bash
$ docker-compose pull
$ docker-compose up -d
```

Cela fonctionne-t-il mieux ?

**Comment by samueltardieu** [comment]
J'ai également rajouté ces informations dans le README.

**Comment by lezioul** [comment]
> Bonsoir.
> 
> Le bot est prévu pour utiliser une base de données non protégée dans le cadre d'un `docker-compose`. La base de données n'est accessible que depuis le docker qui lance le bot sur un réseau virtuel privé, du coup il n'y a pas de problème de sécurité d'accès.
> 
> Il suffit de créer un fichier `.env` contenant les variables `TELEGRAM_TOKEN` et `CONTACT_EMAIL`, puis de récupérer la dernière image (elle est maintenant sur DockerHub, compilée à chaque fois qu'une modification entre dans le dépôt) et de lancer le tout, avec :
> 
> ```shell
> $ docker-compose pull
> $ docker-compose up -d
> ```
> 
> Cela fonctionne-t-il mieux ?

Bonjour,

ok, je vais regarder tout ça, je n'ai jamais utilisé docker :D 
Merci en tout cas.

**Comment by lezioul** [comment]
Fonctionne parfaitement avec docker.
Merci pour les efforts.
