### ISSUE TITLE
Commande /start (pour réinitialisation) "bloque" le bot

### ISSUE THREAD

**Issue by lezioul** [samueltardieu/AusweisBot#52]
Bonjour,

Je fais tourner la dernière version récupérée sur DockerHub et j'ai eu le soucis en voulant tester le bot et réinitialisé les infos saisies en relançant la commande /start
Ensuite, le bot ne répond plus (pour un id telegram donné) mais continue de fonctionner pour les autres utilisateurs.

je mets un extrait du log : 
[ausweis-stderr.log](https://github.com/samueltardieu/AusweisBot/files/5492861/ausweis-stderr.log)

**Comment by samueltardieu** [comment]
C'est dû à des commandes expérimentales que j'ai rajoutées hier. Une correction est en cours de test.

En regardant https://github.com/samueltardieu/AusweisBot/actions il est possible de voir facilement lorsque la nouvelle version sera pushée sur DockerHub, et un `docker-compose pull` la récupérera (cela devrait être dans quelques minutes).

**Comment by samueltardieu** [comment]
Je veux bien à l'occasion un retour comme quoi cela corrige le problème (la version est disponible sur DockerHub).

**Comment by lezioul** [comment]
> C'est dû à des commandes expérimentales que j'ai rajoutées hier. Une correction est en cours de test.
> 
> En regardant https://github.com/samueltardieu/AusweisBot/actions il est possible de voir facilement lorsque la nouvelle version sera pushée sur DockerHub, et un `docker-compose pull` la récupérera (cela devrait être dans quelques minutes).

Je me doutais que c'était lié ;)
J'avais trouvé un workaround en stop/start les services.

J'ai simplement fait un pull effectivement, cela corrige le bug.
Je viens d'en trouver un autre, pas forcément bloquant mais facile à reproduire, j'ouvre une autre issue pour tracking.
