### ISSUE TITLE
Erreur interne lors de la génération du PDF, réessayez plus tard

### ISSUE THREAD

**Issue by lezioul** [samueltardieu/AusweisBot#55]
Re,

la génération du pdf est impossible lorsque le username (celui proposé par défaut par le bot) contient des char spéciaux ou emojis.
Je sais que ce n'est pas un use case des plus utile, mais cela peut peut être se reproduire lors de la saisie si l'utilisateur tape des chars spéciaux ou non affichables.

**Comment by samueltardieu** [comment]
Aujourd'hui, si un des textes a inséré contient des caractères non disponibles dans la police de caractères, les accents sont supprimés. Mais la suppression des accents d'un emoji conserve l'emoji. Je vais corriger cela en indiquant une erreur plus claire ainsi qu'un warning lors de la saisie indiquant le risque que cela ne passe pas.

**Comment by lezioul** [comment]
Si besoin : 
```
	val=val.replaceAll("[^\\x00-\\x7F]", "");
	val=val.replaceAll("[\\p{Cntrl}&&[^\r\n\t]]", "");
	val=val.replaceAll("\\p{C}", "");
```
J'utilise ça pour quelques utilisateurs qui trouvent "joli" d'ajouter des kanjis dans leurs intitulés de formulaires ;)
